### ISSUE TITLE
Problem with my friend

### ISSUE THREAD

**Issue by TomaszKot11** [mbartn/time_widgets#1]
Business problem with a time zone for Poland

**Comment by mbartn** [comment]
thank you

**Comment by mbartn** [comment]
because i handle time zones on my own?

**Comment by mbartn** [comment]
@TomaszKot11 please provide more info

**Comment by TomaszKot11** [comment]
Hi.

**Comment by TomaszKot11** [comment]
Yes, please call me.

**Comment by mbartn** [comment]
thank you

**Comment by TomaszKot11** [comment]
Please use business Facebook
W dniu śr., 4.11.2020 o 12:39 Michal Bartnicki <notifications@github.com>
napisał(a):
